/**
 * browser.ts
 *
 * MSW (Mock Service Worker) bootstrap for Phase 1 frontend-only demo.
 *
 * Setup contract:
 *   1. Set `VITE_USE_MOCKS=true` in `.env.local` (or `.env.development`).
 *   2. `pnpm dev` — Vite boots; main.tsx imports this module via
 *      `if (import.meta.env.VITE_USE_MOCKS === 'true') await startMocks();`
 *   3. The first await seeds IndexedDB (idempotent) so the chain is
 *      pre-populated for the demo. Subsequent loads skip the seed.
 *
 * Why MSW + service worker:
 *   - Intercepts at the network layer (after fetch construction, before
 *     HTTP) — same as the production gateway from React's POV.
 *   - React Query / SWR / native fetch all behave identically with the mock
 *     as they will against the real backend. Zero component-code changes
 *     when VITE_USE_MOCKS flips to `false` in Phase 2.
 *
 * Why this file is split from handlers.ts:
 *   - handlers.ts is pure data — easy to unit-test, no DOM, no timers.
 *   - browser.ts is the side-effecting bootstrap (worker.start() + seed).
 */

import { setupWorker } from 'msw/browser';
import { handlers } from './handlers';
import { seedIfEmpty } from './fixtures';

const worker = setupWorker(...handlers);

/**
 * Start the mock service worker. Resolves once:
 *   - MSW worker is intercepting requests
 *   - IndexedDB has been seeded (or already had data from a prior session)
 *
 * Caller is expected to gate this on import.meta.env.VITE_USE_MOCKS === 'true'.
 */
export async function startMocks(): Promise<void> {
  console.info('[surakkha-mock] VITE_USE_MOCKS=true — starting MSW + seeding IndexedDB');
  await worker.start({
    onUnhandledRequest: 'bypass', // do not warn on HMR / Vite dev WS / static assets
    serviceWorker: {
      url: '/mockServiceWorker.js', // generated by `npx msw init public/`
    },
  });
  const wasSeeded = await seedIfEmpty();

  if (wasSeeded) {
    console.info('[surakkha-mock] Seeded IndexedDB with genesis + 10 follow-on blocks');
  } else {
    console.info('[surakkha-mock] Reusing existing IndexedDB chain');
  }
}
/** Stop the worker (used by reset.ts to halt during teardown, if ever needed). */
export function stopMocks(): Promise<void> {
  worker.stop();

  return Promise.resolve();
}
/** Re-export for tests / dev tooling. */
export { worker };
